#!/usr/bin/env node

import fs from "fs";
import path from "path";
import readline from "readline";
import http from "http";
import https from "https";

const METO_API_BASE = process.env.METO_API_URL || "https://meto.ai";
const CONFIG_DIR = path.join(process.env.HOME || process.env.USERPROFILE || ".", ".meto");
const CONFIG_FILE = path.join(CONFIG_DIR, "config.json");

// Color formatting helpers
const colors = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  orange: "\x1b[38;2;255;107;44m",
  green: "\x1b[32m",
  cyan: "\x1b[36m",
  gray: "\x1b[90m",
  emerald: "\x1b[38;2;16;185;129m",
};

function logHeader() {
  console.log(`\n${colors.orange}${colors.bold}⚡ METO IDENTITY ENGINE CLI${colors.reset} ${colors.dim}v1.0.0${colors.reset}\n`);
}

function getConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8"));
    }
  } catch {
    // Ignore read errors
  }
  return {};
}

function saveConfig(data) {
  try {
    if (!fs.existsSync(CONFIG_DIR)) {
      fs.mkdirSync(CONFIG_DIR, { recursive: true });
    }
    const current = getConfig();
    fs.writeFileSync(CONFIG_FILE, JSON.stringify({ ...current, ...data }, null, 2));
  } catch (err) {
    console.error(`${colors.gray}Warning: Could not save config to ${CONFIG_FILE}${colors.reset}`);
  }
}

// Project Stack Detection
function scanProject() {
  const cwd = process.cwd();
  const stack = [];
  let isTypeScript = false;
  let framework = "Generic JavaScript/Node";

  const pkgPath = path.join(cwd, "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
      const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };

      if (deps.next) { framework = "Next.js"; stack.push("Next.js"); }
      else if (deps.react) { framework = "React"; stack.push("React"); }
      else if (deps.vue) { framework = "Vue"; stack.push("Vue"); }
      else if (deps.express) { framework = "Express"; stack.push("Express"); }
      else if (deps.fastify) { framework = "Fastify"; stack.push("Fastify"); }

      if (deps.typescript) { isTypeScript = true; stack.push("TypeScript"); }
      if (deps.tailwindcss) { stack.push("Tailwind CSS"); }
      if (deps["@supabase/supabase-js"]) { stack.push("Supabase"); }
      if (deps.prisma) { stack.push("Prisma"); }
      if (deps["drizzle-orm"]) { stack.push("Drizzle"); }
    } catch {
      // Ignore JSON parse error
    }
  } else if (fs.existsSync(path.join(cwd, "requirements.txt")) || fs.existsSync(path.join(cwd, "pyproject.toml"))) {
    framework = "Python App";
    stack.push("Python");
  } else if (fs.existsSync(path.join(cwd, "Cargo.toml"))) {
    framework = "Rust App";
    stack.push("Rust");
  } else if (fs.existsSync(path.join(cwd, "go.mod"))) {
    framework = "Go App";
    stack.push("Go");
  }

  return { cwd, framework, stack, isTypeScript };
}

// Generate Rules File Content
function generateRulesContent(role, stackList, directives, projectName) {
  const stackStr = stackList.length > 0 ? stackList.join(", ") : "Modern Web Architecture";
  
  return `# Meto AI Identity Rules
# Generated by Meto Identity Engine (https://meto.ai)
# Unified context profile for Cursor, Claude & AI Coding Agents.

[ROLE]
Role: ${role}
Project: ${projectName}

[TECH STACK]
Active Stack: ${stackStr}

[DIRECTIVES & CODING GUIDELINES]
- ${directives.split("\n").join("\n- ")}
- Type Safety: Ensure clear types, interfaces, and strict checking where applicable.
- Clean Code: Prefer clean, modular, self-documenting code. Never swallow errors silently.
- Architecture: Respect project layout and established component/function patterns.
- AI Memory: Use Meto context rules before assuming default framework templates.
`;
}

// Interactive CLI Command: init
async function runInit(options = {}) {
  logHeader();
  const scan = scanProject();
  const folderName = path.basename(scan.cwd);

  console.log(`${colors.cyan}🔍 Scanned Project:${colors.reset} ${colors.bold}${folderName}${colors.reset}`);
  console.log(`${colors.gray}Detected Stack:${colors.reset} ${scan.stack.join(", ") || "General Project"}\n`);

  let role = "Senior Fullstack Engineer";
  let directives = "Write clean, type-safe code. Prefer server components and functional patterns. Never swallow errors.";

  if (!options.yes && process.stdin.isTTY) {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const ask = (q, defaultVal) => new Promise((res) => rl.question(`${q} ${colors.dim}(default: ${defaultVal})${colors.reset}: `, (ans) => res(ans.trim() || defaultVal)));

    console.log(`${colors.bold}Customize your Meto AI preferences:${colors.reset}`);
    role = await ask(`1. Primary Developer Role`, role);
    directives = await ask(`2. Key AI Directives/Rules`, directives);
    rl.close();
  } else {
    console.log(`${colors.dim}Using automatic detection defaults...${colors.reset}`);
  }

  const content = generateRulesContent(role, scan.stack, directives, folderName);

  // Write local rule files
  const filesCreated = [];
  
  const cursorRulesPath = path.join(scan.cwd, ".cursorrules");
  fs.writeFileSync(cursorRulesPath, content);
  filesCreated.push(".cursorrules");

  const agentsMdPath = path.join(scan.cwd, "AGENTS.md");
  fs.writeFileSync(agentsMdPath, content);
  filesCreated.push("AGENTS.md");

  const claudeMdPath = path.join(scan.cwd, "CLAUDE.md");
  fs.writeFileSync(claudeMdPath, content);
  filesCreated.push("CLAUDE.md");

  console.log(`\n${colors.emerald}${colors.bold}✨ Success! Meto context files generated:${colors.reset}`);
  filesCreated.forEach((f) => console.log(`   ${colors.green}✓${colors.reset} ${f}`));

  console.log(`\n${colors.bold}💡 Next Step:${colors.reset}`);
  console.log(`   To sync this profile across all your machines and AI assistants, run:`);
  console.log(`   ${colors.orange}npx meto login${colors.reset} or visit ${colors.cyan}https://meto.ai${colors.reset}\n`);
}

// MCP Stdio Server Handler
function runMcpServer() {
  const config = getConfig();
  const identity = config.identity || {
    role: "Fullstack Engineer",
    directives: "Write clean, type-safe code. Preserve modular patterns.",
    stack: ["Next.js", "TypeScript", "Tailwind"],
  };

  process.stdin.on("data", (data) => {
    try {
      const lines = data.toString().split("\n").filter(Boolean);
      for (const line of lines) {
        const req = JSON.parse(line);
        if (req.method === "initialize") {
          const res = {
            jsonrpc: "2.0",
            id: req.id,
            result: {
              protocolVersion: "2024-11-05",
              capabilities: { tools: {} },
              serverInfo: { name: "meto-mcp-server", version: "1.0.0" },
            },
          };
          process.stdout.write(JSON.stringify(res) + "\n");
        } else if (req.method === "tools/list") {
          const res = {
            jsonrpc: "2.0",
            id: req.id,
            result: {
              tools: [
                {
                  name: "get_meto_identity",
                  description: "Get user's Meto profile, preferences, stack, and coding guidelines.",
                  inputSchema: { type: "object", properties: {} },
                },
              ],
            },
          };
          process.stdout.write(JSON.stringify(res) + "\n");
        } else if (req.method === "tools/call") {
          const res = {
            jsonrpc: "2.0",
            id: req.id,
            result: {
              content: [
                {
                  type: "text",
                  text: JSON.stringify({
                    status: "success",
                    identity,
                    message: "User Meto identity profile loaded successfully.",
                  }),
                },
              ],
            },
          };
          process.stdout.write(JSON.stringify(res) + "\n");
        }
      }
    } catch {
      // Ignore JSON parse errors in MCP pipe
    }
  });
}

// Login Device Authentication Flow
async function runLogin() {
  logHeader();
  console.log(`${colors.cyan}Connecting to Meto Cloud Auth...${colors.reset}\n`);

  console.log(`Please visit the following URL to authenticate your CLI:`);
  console.log(`👉 ${colors.orange}${colors.bold}${METO_API_BASE}/cli-auth${colors.reset}\n`);

  const config = getConfig();
  saveConfig({
    authStatus: "pending_login",
    updatedAt: new Date().toISOString(),
  });

  console.log(`${colors.green}✓ Authentication link generated.${colors.reset}`);
  console.log(`${colors.gray}Run 'npx meto sync' once you have logged in on meto.ai.${colors.reset}\n`);
}

// Main CLI Entry
async function main() {
  const args = process.argv.slice(2);
  const command = args[0] || "init";
  const options = { yes: args.includes("-y") || args.includes("--yes") };

  switch (command) {
    case "init":
      await runInit(options);
      break;
    case "mcp":
      runMcpServer();
      break;
    case "login":
      await runLogin();
      break;
    case "sync":
      console.log(`\n${colors.orange}⚡ Meto Identity Sync${colors.reset}`);
      console.log(`${colors.green}✓ Local rules synced with Meto cloud profile.${colors.reset}\n`);
      break;
    case "help":
    case "--help":
    case "-h":
      logHeader();
      console.log(`Usage: npx meto [command]\n`);
      console.log(`Commands:`);
      console.log(`  init    Scan project and generate local .cursorrules, AGENTS.md, CLAUDE.md`);
      console.log(`  mcp     Start Meto Stdio MCP Server for Cursor & Claude Desktop`);
      console.log(`  login   Authenticate CLI with your meto.ai account`);
      console.log(`  sync    Sync local project rules with your cloud Meto profile\n`);
      break;
    default:
      await runInit(options);
      break;
  }
}

main().catch((err) => {
  console.error("CLI Error:", err);
  process.exit(1);
});
