import type { Project } from "@/lib/projects/types";
import type { KnowledgeObject } from "@/lib/knowledge/types";

export type GeneratedDoc = {
  id: string;
  title: string;
  filename: string;
  content: string;
};

function memoryText(
  memoriesByRole: Record<string, KnowledgeObject[]>,
  role: string
): string {
  return (memoriesByRole[role] ?? [])
    .map((m) => m.content.trim())
    .filter(Boolean)
    .join("\n\n");
}

export function generateProjectDocs(
  project: Project,
  memoriesByRole: Record<string, KnowledgeObject[]>
): GeneratedDoc[] {
  const stack = memoryText(memoriesByRole, "stack");
  const architecture = memoryText(memoriesByRole, "architecture");
  const deployment = memoryText(memoriesByRole, "deployment");
  const rules = memoryText(memoriesByRole, "rules");
  const business = memoryText(memoriesByRole, "business");
  const api = memoryText(memoriesByRole, "api");
  const focus = project.current_focus ?? {};

  const readme = `# ${project.name}

${project.description || "Auto-generated from Meto project memory."}

## Tech stack

${stack || "_Run import & scan to populate._"}

## Architecture

${architecture || "_Pending repository scan._"}

## Getting started

1. Clone the repository
2. Install dependencies (\`npm install\` / \`pnpm install\`)
3. Copy environment variables (see Environment guide)
4. Run the dev server

## Current focus

${focus.sprint ? `- **Sprint:** ${focus.sprint}` : ""}
${focus.current_task ? `- **Task:** ${focus.current_task}` : ""}
${focus.blockers?.length ? `- **Blockers:** ${focus.blockers.join(", ")}` : ""}

---
_Generated by Meto — living documentation synced from project memory._
`;

  const contributing = `# Contributing to ${project.name}

## Coding conventions

${rules || "- Follow patterns in existing code\n- Prefer Server Actions for mutations\n- Use Tailwind for styling"}

## Architecture notes

${architecture || "_See README architecture section._"}

## Before opening a PR

- [ ] Changes match project stack and rules
- [ ] No secrets committed
- [ ] Meto project memory updated if architecture changed
`;

  const envGuide = `# Environment setup — ${project.name}

Detected stack (names only — never commit secrets):

${stack || "_Scan repo to infer required services._"}

## Typical variables

- Database URL / Supabase URL and anon key
- Auth provider keys (Clerk, Supabase, etc.)
- API keys for third-party services

Copy \`.env.example\` if present, or ask Meto MCP for \`profile://project/${project.slug}/today\`.
`;

  const deploymentGuide = `# Deployment — ${project.name}

${deployment || "_No deployment manifests detected yet._"}

## Checklist

- [ ] Environment variables set in hosting provider
- [ ] Database migrations applied
- [ ] CI passing on main branch
`;

  const apiDocs = `# API overview — ${project.name}

${api || architecture || "_Rescan after adding route handlers._"}

## MCP context

Agents can read live context via:

- \`profile://project/${project.slug}\` — full project memory
- \`profile://project/${project.slug}/today\` — today's context bundle
`;

  const onboarding = `# Onboarding — ${project.name}

Welcome! This guide gets you productive in under 60 seconds.

## What we're building

${business || project.description || "_Add business context in Meto Projects._"}

## Stack at a glance

${stack || "_Import repo in Meto._"}

## Connect your AI

1. Open Meto → MCP
2. Install in Cursor / Claude Desktop
3. Read \`profile://project/${project.slug}/today\` before coding
`;

  return [
    { id: "readme", title: "README", filename: "README.md", content: readme.trim() },
    {
      id: "contributing",
      title: "Contributing",
      filename: "CONTRIBUTING.md",
      content: contributing.trim(),
    },
    {
      id: "env",
      title: "Environment guide",
      filename: "docs/ENVIRONMENT.md",
      content: envGuide.trim(),
    },
    {
      id: "deployment",
      title: "Deployment guide",
      filename: "docs/DEPLOYMENT.md",
      content: deploymentGuide.trim(),
    },
    { id: "api", title: "API docs", filename: "docs/API.md", content: apiDocs.trim() },
    {
      id: "onboarding",
      title: "Onboarding guide",
      filename: "docs/ONBOARDING.md",
      content: onboarding.trim(),
    },
  ];
}
